import fs from "node:fs/promises";
import path from "node:path";

const bbox = {
  south: 40.2623896,
  north: 40.3316825,
  west: 69.5612523,
  east: 69.6740681,
};

const center = { lat: 40.2842191, lon: 69.6191174 };
const cellSizeMeters = 650;
const outputPath = path.resolve("src/data/generated/scientificHotspots.ts");
const overpassEndpoints = [
  "https://overpass-api.de/api/interpreter",
  "https://overpass.kumi.systems/api/interpreter",
  "https://overpass.openstreetmap.ru/cgi/interpreter",
];

const weights = {
  surfaceHeatProxy: 0.35,
  lowShadeProxy: 0.2,
  populationExposureProxy: 0.2,
  vulnerableFacilities: 0.15,
  transportMarketExposure: 0.1,
};

const riskZoneAnchors = [
  { id: "panjshanbe-market", lat: 40.2829, lon: 69.6277, type: "market", strength: 1 },
  { id: "central-clinics", lat: 40.2867, lon: 69.6206, type: "health", strength: 0.92 },
  { id: "school-microdistrict", lat: 40.2939, lon: 69.6098, type: "school", strength: 0.84 },
  { id: "dense-residential-east", lat: 40.2794, lon: 69.6555, type: "residential", strength: 0.88 },
  { id: "transport-corridor", lat: 40.2716, lon: 69.6116, type: "transport", strength: 0.86 },
  { id: "syr-darya-cooling", lat: 40.3004, lon: 69.6101, type: "cooling", strength: 0.6 },
];

const riverCorridor = [
  [40.305, 69.575],
  [40.302, 69.592],
  [40.298, 69.608],
  [40.292, 69.627],
  [40.287, 69.648],
  [40.282, 69.668],
];

const layerQueries = {
  buildings: `way["building"](${bboxString()});out center qt;`,
  markets: `nwr["amenity"="marketplace"](${bboxString()});out center tags qt;`,
  parks: `nwr["leisure"="park"](${bboxString()});out center tags qt;`,
  education: `nwr["amenity"~"school|kindergarten|college|university"](${bboxString()});out center tags qt;`,
  health: `(nwr["healthcare"](${bboxString()});nwr["amenity"~"hospital|clinic|pharmacy|doctors|dentist"](${bboxString()}););out center tags qt;`,
  transit: `(node["highway"="bus_stop"](${bboxString()});nwr["public_transport"~"platform|stop_position"](${bboxString()}););out center tags qt;`,
};

async function main() {
  const layers = {};
  const sourceCounts = {};
  const failures = [];

  for (const [layer, query] of Object.entries(layerQueries)) {
    try {
      const elements = await fetchOverpass(query);
      const points = elements.map(osmPoint).filter(Boolean);
      layers[layer] = points;
      sourceCounts[layer] = points.length;
      await wait(1600);
    } catch (error) {
      layers[layer] = [];
      sourceCounts[layer] = 0;
      failures.push(`${layer}: ${error.message || String(error)}`);
    }
  }

  const grid = buildGrid();
  const buildingDensities = grid.map((cell) => countWithin(cell.center, layers.buildings, 520));
  const maxBuildingDensity = Math.max(1, ...buildingDensities);
  const cells = grid.map((cell, index) => scoreCell(cell, layers, buildingDensities[index] / maxBuildingDensity));
  const topCells = [...cells].sort((a, b) => b.score0to100 - a.score0to100).slice(0, 8);

  const file = [
    "/* This file is generated by scripts/generateScientificHotspots.mjs. */",
    "export type ScientificRiskCell = {",
    "  id: string;",
    "  center: [number, number];",
    "  boundary: [number, number][];",
    "  score0to100: number;",
    "  riskLevel0to4: 0 | 1 | 2 | 3 | 4;",
    "  components: {",
    "    surfaceHeatProxy: number;",
    "    lowShadeProxy: number;",
    "    populationExposureProxy: number;",
    "    vulnerableFacilities: number;",
    "    transportMarketExposure: number;",
    "  };",
    "  drivers: string[];",
    "  confidence: \"OSM-derived proxy\" | \"mixed proxy\";",
    "};",
    "",
    `export const scientificModel = ${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        modelVersion: "scientific-grid-v0.2-osm-proxy",
        cellSizeMeters,
        bbox,
        weights,
        sourceCounts,
        overpassFailures: failures,
        integratedLayers: [
          "OSM buildings inside Khujand bbox",
          "OSM schools/kindergartens/universities",
          "OSM healthcare/pharmacies/clinics",
          "OSM markets",
          "OSM bus stops/public transport points",
          ...(sourceCounts.parks > 0 ? ["OSM parks"] : []),
          "Open-Meteo hourly weather is applied live elsewhere in the dashboard",
        ],
        proxyLayers: [
          "Surface heat uses building density + market/transport proximity until Landsat LST is processed",
          "Low shade uses river/cooling-corridor proximity + building density until Sentinel-2 NDVI/NDWI is processed",
          "Population exposure uses building density + residential/market proximity until WorldPop raster is processed",
        ],
        missingValidatedLayers: [
          "Landsat land surface temperature raster",
          "Sentinel-2 NDVI/NDWI/NDBI raster",
          "WorldPop 100 m population raster",
          "Tajik Hydromet station or warning feed",
          "Local field sensor observations",
        ],
        topCellIds: topCells.map((cell) => cell.id),
        cells,
      },
      null,
      2,
    )} as const;`,
    "",
  ].join("\n");

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, file, "utf8");
  console.log(`Wrote ${cells.length} cells to ${outputPath}`);
  console.log(JSON.stringify({ sourceCounts, failures, topCellIds: topCells.map((cell) => cell.id) }, null, 2));
}

function scoreCell(cell, layers, buildingDensity) {
  const nearestMarket = nearestDistance(cell.center, layers.markets);
  const nearestTransit = nearestDistance(cell.center, layers.transit);
  const nearestHealth = nearestDistance(cell.center, layers.health);
  const nearestEducation = nearestDistance(cell.center, layers.education);
  const nearestPark = nearestDistance(cell.center, layers.parks);
  const nearestRiver = nearestPolylineDistance(cell.center, riverCorridor);
  const marketAnchor = anchorInfluence(cell.center, "market", 1150);
  const residentialAnchor = anchorInfluence(cell.center, "residential", 1250);
  const transportAnchor = anchorInfluence(cell.center, "transport", 1150);
  const coolingAnchor = anchorInfluence(cell.center, "cooling", 1450);

  const marketProximity = proximity(nearestMarket, 950);
  const transitProximity = Math.max(proximity(nearestTransit, 700), transportAnchor);
  const vulnerableFacilities = Math.max(proximity(nearestHealth, 900), proximity(nearestEducation, 900), anchorInfluence(cell.center, "health", 950), anchorInfluence(cell.center, "school", 950));
  const coolingProximity = Math.max(proximity(nearestPark, 650), proximity(nearestRiver, 580), coolingAnchor);

  const components = {
    surfaceHeatProxy: clamp01(0.7 * buildingDensity + 0.18 * transitProximity + 0.12 * marketProximity),
    lowShadeProxy: clamp01(0.62 * buildingDensity + 0.38 * (1 - coolingProximity)),
    populationExposureProxy: clamp01(0.72 * buildingDensity + 0.18 * residentialAnchor + 0.1 * marketAnchor),
    vulnerableFacilities: clamp01(vulnerableFacilities),
    transportMarketExposure: clamp01(Math.max(marketProximity, marketAnchor) * 0.58 + transitProximity * 0.42),
  };

  const rawScore = Object.entries(weights).reduce((sum, [key, weight]) => sum + components[key] * weight, 0);
  const score0to100 = Math.round(clamp01(rawScore) * 100);

  return {
    id: cell.id,
    center: roundPoint(cell.center),
    boundary: cell.boundary.map(roundPoint),
    score0to100,
    riskLevel0to4: riskLevel(score0to100),
    components: Object.fromEntries(Object.entries(components).map(([key, value]) => [key, Number(value.toFixed(3))])),
    drivers: topDrivers(components),
    confidence: "OSM-derived proxy",
  };
}

function buildGrid() {
  const latStep = cellSizeMeters / 111_320;
  const lonStep = cellSizeMeters / (111_320 * Math.cos((center.lat * Math.PI) / 180));
  const cells = [];
  let row = 0;

  for (let south = bbox.south; south < bbox.north; south += latStep) {
    let col = 0;
    const north = Math.min(bbox.north, south + latStep);
    for (let west = bbox.west; west < bbox.east; west += lonStep) {
      const east = Math.min(bbox.east, west + lonStep);
      cells.push({
        id: `cell-r${String(row).padStart(2, "0")}-c${String(col).padStart(2, "0")}`,
        center: [(south + north) / 2, (west + east) / 2],
        boundary: [
          [south, west],
          [south, east],
          [north, east],
          [north, west],
        ],
      });
      col += 1;
    }
    row += 1;
  }

  return cells;
}

async function fetchOverpass(query) {
  const body = new URLSearchParams({ data: `[out:json][timeout:40];${query}` });

  const errors = [];
  for (const endpoint of overpassEndpoints) {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": "HeatShieldKhujand/0.2 scientific prototype",
      },
      body,
    });

    const text = await response.text();
    if (!response.ok) {
      errors.push(`${endpoint} ${response.status}: ${text.slice(0, 120)}`);
      await wait(1200);
      continue;
    }

    const payload = JSON.parse(text);
    return payload.elements ?? [];
  }

  throw new Error(errors.join(" | "));
}

function osmPoint(element) {
  const lat = element.lat ?? element.center?.lat;
  const lon = element.lon ?? element.center?.lon;
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return undefined;
  return { lat, lon };
}

function bboxString() {
  return `${bbox.south},${bbox.west},${bbox.north},${bbox.east}`;
}

function countWithin(origin, points, radiusMeters) {
  return points.reduce((count, point) => count + (distanceMeters(origin, [point.lat, point.lon]) <= radiusMeters ? 1 : 0), 0);
}

function nearestDistance(origin, points) {
  if (!points.length) return Number.POSITIVE_INFINITY;
  return points.reduce((nearest, point) => Math.min(nearest, distanceMeters(origin, [point.lat, point.lon])), Number.POSITIVE_INFINITY);
}

function nearestPolylineDistance(origin, path) {
  return path.reduce((nearest, point) => Math.min(nearest, distanceMeters(origin, point)), Number.POSITIVE_INFINITY);
}

function anchorInfluence(origin, type, scaleMeters) {
  return riskZoneAnchors
    .filter((anchor) => anchor.type === type)
    .reduce((best, anchor) => {
      const influence = proximity(distanceMeters(origin, [anchor.lat, anchor.lon]), scaleMeters) * anchor.strength;
      return Math.max(best, influence);
    }, 0);
}

function proximity(distance, scaleMeters) {
  if (!Number.isFinite(distance)) return 0;
  return Math.exp(-distance / scaleMeters);
}

function distanceMeters(a, b) {
  const radius = 6_371_000;
  const lat1 = (a[0] * Math.PI) / 180;
  const lat2 = (b[0] * Math.PI) / 180;
  const dLat = ((b[0] - a[0]) * Math.PI) / 180;
  const dLon = ((b[1] - a[1]) * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  return 2 * radius * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

function topDrivers(components) {
  const labels = {
    surfaceHeatProxy: "built-surface heat proxy",
    lowShadeProxy: "low shade / cooling access",
    populationExposureProxy: "population exposure proxy",
    vulnerableFacilities: "near schools or health facilities",
    transportMarketExposure: "market / transport exposure",
  };

  return Object.entries(components)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([key]) => labels[key]);
}

function riskLevel(score) {
  if (score >= 82) return 4;
  if (score >= 66) return 3;
  if (score >= 48) return 2;
  if (score >= 30) return 1;
  return 0;
}

function roundPoint(point) {
  return [Number(point[0].toFixed(6)), Number(point[1].toFixed(6))];
}

function clamp01(value) {
  return Math.max(0, Math.min(1, value));
}

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
